project:
  type: website
  output-dir: docs

website:
  title: "Joaquin Cavieres"
  navbar:
    left: 
      - index.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jcavieresg
      - icon: twitter
        href: https://x.com/jcavieresg
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

exclude:
- posts/post-with-code

