project:
  type: website
  output-dir: docs

website:
  title: "Joaquin Cavieres"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jcavieresg
      - icon: twitter
        href: https://x.com/jcavieresg
      - text: "CV""
        href: posts/CV_Joaquin_Cavieres.pdf
format:
  html:
    theme: cyborg
    css: styles.css

editor: visual

exclude:
- posts/post-with-code

